apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmug-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      project: vmug-demo
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        project: vmug-demo
    spec:
      containers:
      - name: vmug-cntnr
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        image: joehoughes/vmugapp:1.1

