apiVersion: v1
kind: Service
metadata:
  name: svc-vmug-local
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 32000
  selector:
    project: vmug-demo

